warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java

Remove comment

---

warehouse/query-core/src/main/java/datawave/query/iterator/FunctionIterator.java

Remove empty class

---

BUILDME.md

Let me know if you agree with this change.

Resolves issue #16 to Change order of Readme

---

warehouse/query-core/src/main/java/datawave/query/jexl/DatawaveInterpreter.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TreeFlatteningRebuildingVisitor.java
warehouse/query-core/src/test/java/datawave/query/jexl/DatawaveInterpreterTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/visitors/TreeFlatteningRebuildingVisitorTest.java

Ran into some issues today with the TreeFlatteningRebuildingVisitor and the DatawaveInterpreter.  Let me know what you think.

Whit-erpreter

---

warehouse/ingest-wikipedia/src/main/java/datawave/ingest/wikipedia/WikipediaInputFormat.java

Change the extension and remove the split since it isn't necessary.

Closes #52: Resolved issue with wikipedia input format

---

web-services/query/src/test/java/datawave/webservice/query/runner/QueryExecutorBeanTest.java

Added more tests in order to address [this comment](https://github.com/NationalSecurityAgency/datawave/pull/90#issuecomment-391439085).
All tests pass when running `mvn clean install`

Add a couple more tests to verify queries with null dates do not break

---

warehouse/core/src/test/java/datawave/iterators/filter/ageoff/EdgeMetadataCQStripperCombinerTest.java
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/edge/EdgeKeyVersioningCache.java
warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/handler/shard/NumShardsTest.java
warehouse/metrics-core/src/main/java/datawave/metrics/util/UpgradeCounterValues.java
warehouse/query-core/src/main/java/datawave/webservice/modification/MutableMetadataHandler.java
web-services/common-util/src/test/java/datawave/query/iterator/QueriesTableAgeOffIteratorTest.java

Close will flush before closing the BatchWriter.

Remove redundant batchwriter flush

---

warehouse/core/src/main/java/datawave/mr/bulk/split/RangeSplit.java

I believe there should be an `else` here

Fixing missing else in RangeSplit

---

web-services/query/src/main/java/datawave/webservice/query/util/QueryMetricsReporter.java

Missed this one in the last PR.

Updated QueryMetricsReporter to make use of PasswordConverter

---

warehouse/core/src/main/java/datawave/iterators/EdgeMetadataCombiner.java
warehouse/core/src/test/java/datawave/iterators/EdgeMetadataCombinerTest.java
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/edge/ProtobufEdgeDataTypeHandler.java

Fixes duplicate entries appearing in the edge metadata.

Fixed duplicate edge entries in the metadata table

---

warehouse/query-core/src/main/java/datawave/query/QueryParameters.java
warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfigurationFactory.java
warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
warehouse/query-core/src/main/java/datawave/query/iterator/pipeline/BatchedDocumentIterator.java
warehouse/query-core/src/main/java/datawave/query/iterator/pipeline/Pipeline.java
warehouse/query-core/src/main/java/datawave/query/iterator/pipeline/PipelineIterator.java
warehouse/query-core/src/main/java/datawave/query/iterator/pipeline/SerialIterator.java
warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctions.java
warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
warehouse/query-core/src/main/java/datawave/query/planner/QueryOptionsSwitch.java
warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java
warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java
warehouse/query-core/src/test/java/datawave/query/GroupingTest.java
warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml

adds parameter to control grouping batch size on tserver

Batch grouping

---

pom.xml
warehouse/core/pom.xml
warehouse/core/src/main/java/datawave/util/cli/AccumuloArgs.java
warehouse/core/src/test/java/datawave/util/cli/AccumuloArgsTest.java

For use with the jcommander library.
Updated jcommander library version to take advantage of new features
that allow the resuse and composition of argument objects
Added explicit dependency on jcommander in datawave-core

Added AccumuloArgs class to hold common args

---

warehouse/core/pom.xml
warehouse/core/src/main/java/datawave/ingest/util/cache/watch/FileRuleWatcher.java
warehouse/core/src/main/java/datawave/iterators/filter/ConfigurableAgeOffFilter.java
warehouse/core/src/test/java/datawave/ingest/util/cache/watch/FileRuleLoadContentsMergeFiltersTest.java
warehouse/core/src/test/java/datawave/ingest/util/cache/watch/TestFilter.java
warehouse/core/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java
warehouse/core/src/test/resources/test-root-rules.xml

Added clarifying comments to class as some of the workings can be difficult to follow
Added unit tests as there were none

Important Fix for FileRuleWatcher

---

warehouse/ingest-core/pom.xml
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoader.java
warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoaderTest.java

exit the loader when shutdown port already taken and make running flag observable between threads

MapFileLoaderShutdownBug

---

warehouse/core/src/main/java/datawave/ingest/util/cache/watch/FileRuleWatcher.java
warehouse/core/src/main/java/datawave/iterators/filter/ConfigurableAgeOffFilter.java
warehouse/core/src/main/java/datawave/iterators/filter/RegexFilterBase.java
warehouse/core/src/main/java/datawave/iterators/filter/TokenFilterBase.java
warehouse/core/src/main/java/datawave/iterators/filter/TokenizingFilterBase.java
warehouse/core/src/main/java/datawave/iterators/filter/ageoff/AppliedRule.java
warehouse/core/src/main/java/datawave/iterators/filter/ageoff/DataTypeAgeOffFilter.java
warehouse/core/src/main/java/datawave/iterators/filter/ageoff/FieldAgeOffFilter.java
warehouse/core/src/main/java/datawave/iterators/filter/ageoff/FilterRule.java
warehouse/core/src/main/java/datawave/iterators/filter/ageoff/MaximumAgeOffFilter.java
warehouse/core/src/test/java/datawave/ingest/util/cache/watch/TestDataTypeFilter.java
warehouse/core/src/test/java/datawave/ingest/util/cache/watch/TestFieldFilter.java
warehouse/core/src/test/java/datawave/ingest/util/cache/watch/TestFilter.java
warehouse/core/src/test/java/datawave/iterators/filter/ageoff/FieldAgeOffFilterTest.java
warehouse/query-core/src/main/java/datawave/query/jexl/JexlRule.java

make IteratorEnvironment available to filters

MakeIterEnvAvailableToFilters

---

warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java

Flatten portion of visit(EQNode) method in the RangeStream class for readability.

Flatten portion of visit(EQNode) method in the RangeStream class

---

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableExpansionVisitor.java
warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
warehouse/query-core/src/test/java/datawave/query/PushdownQueryTest.java
warehouse/query-core/src/test/java/datawave/query/RangeQueryTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableExpansionVisitorTest.java
warehouse/query-core/src/test/java/datawave/query/util/WiseGuysIngest.java

DATAWAVE-265: Add ExecutableExpansionVisitor

---

warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/DefaultTokenSearch.java
warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/StandardAnalyzer.java
warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/StandardTokenizer.java
warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/TokenSearch.java
warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/TokenizationHelper.java
warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/TruncateAttributeImpl.java
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/tokenize/ExtendedContentIndexingColumnBasedHandler.java
warehouse/ingest-core/src/main/java/datawave/ingest/util/NGramTokenizationStrategy.java
warehouse/ingest-wikipedia/src/main/java/datawave/ingest/wikipedia/WikipediaDataTypeHandler.java
warehouse/pom.xml
warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexListIteratorJexl.java
warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/RegexpQueryNodeBuilder.java
warehouse/query-core/src/main/java/datawave/query/language/parser/jexl/LuceneToJexlQueryParser.java
warehouse/query-core/src/main/java/datawave/query/language/parser/lucene/FastCharStream.java
warehouse/query-core/src/main/java/datawave/query/language/parser/lucene/QueryConfigHandler.java
warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomFieldLimiterNodeProcessor.java
warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomQueryNodeProcessorPipeline.java
warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomWildcardQueryNodeProcessor.java
warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/TokenizedFieldsAttributeImpl.java
warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java

Fixes #234 - Upgrade Lucene Dependency to 7.5.0 (rebase/squash of #238)

---

services/audit-service/src/main/java/datawave/microservice/audit/config/AuditProperties.java
services/audit-service/src/main/java/datawave/microservice/audit/controller/AuditController.java
services/audit-service/src/test/java/datawave/microservice/audit/AuditServiceTest.java

Assuming this is approved/merged, I can create and tag a new audit-service release.

Added configurable retry logic to the audit service.

---

warehouse/query-core/src/main/java/datawave/query/predicate/TLDEventDataFilter.java
warehouse/query-core/src/test/java/datawave/query/predicate/TLDEventDataFilterTest.java

DATAWAVE-271: Fix fieldName parsing for tf and fi keys

---

warehouse/ingest-core/src/main/java/datawave/ingest/data/config/ingest/IngestFieldFilter.java
warehouse/ingest-core/src/test/java/datawave/ingest/data/config/ingest/IngestFieldFilterTest.java

* Updated the IngestFieldFilter to compare values as configured
* Updated the IngestFieldFilter to handle groups of fields to keep or drop
* Kept the functionality backward compatible with the original code
* Added test cases for all additional functionality

fixes #320: IngestFieldFilter to handle values

---

properties/default.properties
web-services/assert-plugin/required-properties.txt
web-services/deploy/application/src/main/wildfly/add-datawave-configuration.cli

DATAWAVE-340: Allow configuration of wildfly io/worker threads

---

warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
warehouse/query-core/src/main/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctions.java
warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/AtomValuesMatchFunction.java
warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/GetAllMatches.java
warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/Jexl.java
warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/MatchesAtLeastCountOf.java
warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/MatchesInGroupFunction.java
warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/MatchesInGroupLeft.java
warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/OccurrenceFunction.java
warehouse/query-core/src/test/java/datawave/query/CompositeFunctionsTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctionsTest.java

modified:   warehouse/query-core/src/main/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctions.java
new file:   warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
modified:   warehouse/query-core/src/test/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctionsTest.java

grouping tests and fixes

---

pom.xml
services/accumulo-utils/src/main/java/datawave/marking/MarkingFunctions.java
services/accumulo-utils/src/test/java/datawave/marking/MarkingFunctionsDefaultCombineTest.java
warehouse/data-dictionary-core/src/test/java/datawave/webservice/datadictionary/DatawaveDataDictionaryImplTest.java
warehouse/ingest-configuration/src/main/resources/MarkingFunctionsContext.xml
warehouse/ingest-core/src/main/java/datawave/ingest/config/RawRecordContainerImpl.java
warehouse/ingest-core/src/main/java/datawave/ingest/data/config/MarkingsHelper.java
warehouse/ingest-core/src/test/resources/MarkingFunctionsContext.xml
warehouse/query-core/src/main/java/datawave/query/discovery/DiscoveryTransformer.java
warehouse/query-core/src/test/java/datawave/query/IfThisTestFailsThenHitTermsAreBroken.java
warehouse/query-core/src/test/java/datawave/query/UseOccurrenceToCountInJexlContextTest.java
warehouse/query-core/src/test/java/datawave/query/predicate/ValueToAttributesTest.java
warehouse/query-core/src/test/java/datawave/query/tables/IndexQueryLogicTest.java
warehouse/query-core/src/test/java/datawave/query/testframework/AbstractFunctionalQuery.java
web-services/client/src/main/java/datawave/webservice/response/objects/DefaultKey.java
web-services/deploy/configuration/src/main/resources/MarkingFunctionsContext.xml
web-services/query/src/test/java/datawave/webservice/query/logic/TestLegacyBaseQueryLogicTransformer.java
web-services/query/src/test/java/datawave/webservice/query/logic/composite/CompositeQueryLogicTest.java

modified:   pom.xml
modified:   services/accumulo-utils/src/main/java/datawave/marking/MarkingFunctions.java
modified:   warehouse/data-dictionary-core/src/test/java/datawave/webservice/datadictionary/DatawaveDataDictionaryImplTest.java
modified:   warehouse/ingest-configuration/src/main/resources/MarkingFunctionsContext.xml
modified:   warehouse/ingest-core/src/main/java/datawave/ingest/config/RawRecordContainerImpl.java
modified:   warehouse/ingest-core/src/main/java/datawave/ingest/data/config/MarkingsHelper.java
modified:   warehouse/ingest-core/src/test/resources/MarkingFunctionsContext.xml
modified:   warehouse/query-core/src/main/java/datawave/query/discovery/DiscoveryTransformer.java
modified:   warehouse/query-core/src/test/java/datawave/query/IfThisTestFa …

change MarkingFunctions.NoOp name to MarkingFunctions.Default. Add basic implementations for 'combine' methods

---

web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java

modified:   web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java

close query when next gets no results

---

warehouse/query-core/src/main/java/datawave/query/config/LookupUUIDTune.java
warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
web-services/query/src/main/java/datawave/webservice/query/configuration/GenericQueryConfiguration.java
web-services/query/src/main/java/datawave/webservice/query/logic/BaseQueryLogic.java
web-services/query/src/test/java/datawave/webservice/query/configuration/GenericQueryConfigurationMockTest.java
web-services/query/src/test/java/datawave/webservice/query/configuration/TestBaseQueryLogic.java
web-services/query/src/test/java/datawave/webservice/query/configuration/TestLookupUUIDConfiguration.java
web-services/query/src/test/java/datawave/webservice/query/logic/composite/CompositeQueryLogicTest.java

Fix for LookupUUIDTune to persist value of bypassAccumulo via the ShardQueryConfiguration.

Fix for bypassAccumulo in certain cases

---

properties/default.properties
warehouse/query-core/src/main/java/datawave/query/ancestor/AncestorQueryIterator.java
warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
warehouse/query-core/src/main/java/datawave/query/iterator/ParentQueryIterator.java
warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
warehouse/query-core/src/main/java/datawave/query/predicate/AncestorEventDataFilter.java
warehouse/query-core/src/main/java/datawave/query/predicate/ConfigurableEventDataQueryFilter.java
warehouse/query-core/src/main/java/datawave/query/predicate/ParentEventDataFilter.java
warehouse/query-core/src/main/java/datawave/query/predicate/TLDEventDataFilter.java
warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
warehouse/query-core/src/main/java/datawave/query/tld/TLDQueryIterator.java
warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
warehouse/query-core/src/test/java/datawave/query/predicate/TLDEventDataFilterTest.java

DATAWAVE-351: Stop using ConfigurableEventDataQueryFilter

---

warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java

modified:   warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
modified:   warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java

tserver grouping when yielding

---

warehouse/query-core/src/main/java/datawave/query/jexl/lookups/ShardIndexQueryTableStaticMethods.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ParallelIndexExpansion.java
warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
warehouse/query-core/src/test/java/datawave/query/RegexQueryTest.java
warehouse/query-core/src/test/java/datawave/query/testframework/AbstractFunctionalQuery.java

* Push down terms that cannot be expanded against the index
* Ensure we use the correct index based on the regex and which indexes are filled

fixes #372: Forward vs Reverse index

---

warehouse/core/src/main/java/datawave/iterators/filter/AgeOffConfigParams.java
warehouse/core/src/main/java/datawave/iterators/filter/ageoff/AppliedRule.java
warehouse/core/src/main/java/datawave/iterators/filter/ageoff/DataTypeAgeOffFilter.java
warehouse/core/src/main/java/datawave/iterators/filter/ageoff/FieldAgeOffFilter.java
warehouse/core/src/test/java/datawave/iterators/filter/ageoff/FieldAgeOffFilterTest.java

When environment not propigated, the isindextable param would be lost.

Updated AppliedRule to propigate IteratorEnvironment

---

warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
warehouse/query-core/src/main/java/datawave/query/tables/edge/DefaultEdgeEventQueryLogic.java
web-services/query/src/main/java/datawave/webservice/query/configuration/GenericQueryConfiguration.java
web-services/query/src/main/java/datawave/webservice/query/logic/BaseQueryLogic.java
web-services/query/src/test/java/datawave/webservice/query/configuration/GenericQueryConfigurationMockTest.java
web-services/query/src/test/java/datawave/webservice/query/configuration/TestBaseQueryLogic.java

This normalizes all the config options to use getConfig() which is overridden on the way up through the query logics.

fixes #402

---

warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexInfo.java
warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java
warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/IndexInfoTest.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/IntersectionTest.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/UnionTest.java

IndexInfo, Union and Intersection now have unit tests.
They also have small refactors.

IndexInfo, Union and Intersection classes now have unit tests.

---

warehouse/query-core/src/main/java/datawave/query/index/lookup/EntryParser.java
warehouse/query-core/src/main/java/datawave/query/tables/RangeStreamScanner.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/EntryParserTest.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamTest.java
warehouse/query-core/src/test/java/datawave/query/tables/RangeStreamScannerTest.java

Small refactor of RangeStreamScanner.
Unit test for RangeStreamScanner.
Unit test for EntryParser.
Enabled ignored test in the RangeStreamTest.

Expanded Coverage of RangeStreamScanner

---

checkstyle.xml
pom.xml

We use this for checking use of 1.9 API so I thought I would share.  I don't know where it should go though so I just stuck it in the top level pom.

Add checkstyle rule to pom for checking against Accumulo API

---

contrib/datawave-quickstart/bin/services/datawave/bootstrap-web.sh
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/reduce/AggregatingReducer.java

...that prevented Wildfly pid from being found

Closes #425 - AggregatingReducer bug fix. Also fixes quickstart bug

---

warehouse/query-core/src/main/java/datawave/query/util/regex/RegexTrie.java
warehouse/query-core/src/test/java/datawave/query/util/regex/RegexTrieTest.java

- can be used as a simple trie
- will create an equivalent regex from the trie

fixes #422: Created a regextrie

---

warehouse/query-core/src/test/java/datawave/query/util/TypeMetadataProviderLoadingCacheTest.java

Trying to better avoid periodic failures when running this test along side others

Trying to better avoid periodic failures

---

warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorTest.java

Testing helper methods in QueryIterator.

---

warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexMatch.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/IndexMatchTest.java

Continuing to expand coverage of index code.

Added test coverage for IndexMatch.

---

services/type-utils/src/main/java/datawave/query/parser/JavaRegexAnalyzer.java
services/type-utils/src/test/java/datawave/query/parser/JavaRegexAnalyzerTest.java

Updated to handle the quoting and boundary constructs correctly when determining wildcards and literals

fixes #455: Updated to handle the quoting and boundary constructs

---

warehouse/ingest-core/src/main/java/datawave/iterators/PropogatingIterator.java
warehouse/ingest-core/src/test/java/datawave/iterators/PropogatingIteratorSeekTest.java
warehouse/ingest-core/src/test/java/datawave/iterators/PropogatingIteratorTest.java

* Avoid read ahead for non-aggregating column families
* Remove unused code
* minor test cleanup
* Adding test
* formatter changes

Avoid read ahead for non-aggregating column families (#446)

---

common-test/src/main/java/datawave/common/test/utils/query/RangeFactoryForTests.java
warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java
warehouse/query-core/src/main/java/datawave/query/index/lookup/TupleToRange.java
warehouse/query-core/src/main/java/datawave/query/ranges/RangeFactory.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamTest.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/TupleToRangeTest.java
warehouse/query-core/src/test/java/datawave/query/ranges/RangeFactoryTest.java

Renamed RangeFactory to RangeFactoryForTests, 
added RangeFactory for use by TupleToRange, 
added test for TupleToRange and RangeFactory.

Test TupleToRange

---

warehouse/query-core/src/main/java/datawave/query/model/util/LoadModelFromXml.java
warehouse/query-core/src/test/resources/models/CardinalityModel.xml
warehouse/query-core/src/test/resources/models/FakeModelOne.xml
warehouse/query-core/src/test/resources/models/FakeModelTwo.xml
web-services/client/src/main/java/datawave/webservice/model/FieldMapping.java
web-services/client/src/main/java/datawave/webservice/model/Model.java
web-services/model/src/main/java/datawave/webservice/query/model/ModelKeyParser.java
web-services/model/src/test/java/datawave/webservice/query/model/ModelKeyParserTest.java

Removed the requested change to the ModelBean and made all needed changes to webservice usages and ModelKeyParserTest.java

Fixes #477 - Dropped index only column in the model.

---

warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java

Adjusted logging levels and corrected the null appender message by specifying a PatternLayout for the ConsoleAppender.
Fixes #534

Fixes #534 - Logging level update for IngestJob

---

warehouse/query-core/src/main/java/datawave/query/jexl/nodes/TreeHashNode.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TreeHashVisitor.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UniqueExpressionTermsVisitor.java
warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
warehouse/query-core/src/main/java/org/apache/commons/jexl2/parser/JexlNodes.java
warehouse/query-core/src/test/java/datawave/query/jexl/nodes/TreeHashNodeTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/visitors/UniqueExpressionTermsVisitorTest.java

UniqueExpressionTermsVisitor is a visitor that will enforce unique query terms within OR and AND jexl nodes.

Added UniqueExpressionTermsVisitor

---

warehouse/ingest-core/src/main/java/datawave/util/flag/FlagMaker.java

Some simple logging for information on the file to be loaded

Added logging to flagmaker load function

---

web-services/client/src/main/java/datawave/webservice/model/Model.java
web-services/client/src/main/java/datawave/webservice/model/ModelList.java
web-services/deploy/application/src/main/wildfly/add-datawave-configuration.cli
web-services/deploy/application/src/main/wildfly/remove-datawave-configuration.cli
web-services/model/src/main/java/datawave/webservice/query/model/ModelBean.java

Added JQuery support for searching models by title in the Model List page.

Fixes #481 - Add Search to Model Names page

---

warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/TableConfigHelperFactoryTest.java

This will aid in upgrading to 2.0 as Mock was removed.  Related to #533

Replace accumulo MockInstance with MiniAccumuloCluster

---

contrib/in-memory-accumulo/src/main/java/datawave/accumulo/inmemory/InMemoryTableOperations.java
warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownFunction.java
warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownScheduler.java

* The binRanges method was doing the work of tableOps.locate()
* Fix mixing of Accumulo table ID and table name
This is one option to migrate DW to build with Accumulo 2.0.

Replace code in PushdownFunction with Accumulo API

---

pom.xml
warehouse/core/src/main/java/datawave/mr/bulk/split/LocationStrategy.java
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/TermFilter.java
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java
warehouse/query-core/src/main/java/datawave/core/iterators/ResultCountingIterator.java
warehouse/query-core/src/main/java/datawave/mr/bulk/RfileScanner.java
warehouse/query-core/src/main/java/datawave/query/discovery/DiscoveryLogic.java
warehouse/query-core/src/main/java/datawave/query/jexl/lookups/FieldNameLookup.java
warehouse/query-core/src/main/java/datawave/query/jexl/lookups/LookupTermsFromRegex.java
warehouse/query-core/src/main/java/datawave/query/tables/AccumuloResource.java
warehouse/query-core/src/main/java/datawave/query/tables/BatchScannerSession.java
warehouse/query-core/src/main/java/datawave/query/tables/RangeStreamScanner.java
warehouse/query-core/src/main/java/datawave/query/tables/ScannerSession.java
warehouse/query-core/src/main/java/datawave/query/tables/facets/FacetedVisitor.java
warehouse/query-core/src/main/java/datawave/query/tables/facets/MergedReadAhead.java
web-services/common/src/main/java/datawave/webservice/common/cache/SharedBoolean.java
web-services/common/src/main/java/datawave/webservice/common/cache/SharedTriState.java
web-services/query/src/main/java/datawave/webservice/query/configuration/GenericQueryConfiguration.java

* Replaced various dropped methods
* Replaced Stopwatch contstructor & elapsedMillis
* Replaced Iterators.emptyIterator with java Collections
* Catch new IllegalStateException in ScannerSession
This will get DW closer to Accumulo 2.0

Update Guava to 22

---

warehouse/ingest-core/src/main/java/datawave/ingest/util/GenerateShardSplits.java

Add the ability to define the number of shards per splitfor sharded tables.

fix DATAWAVE-631

---

warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexMatch.java
warehouse/query-core/src/test/java/datawave/query/index/lookup/IndexMatchTest.java

Addresses https://github.com/NationalSecurityAgency/datawave/issues/641

Test read/write methods for the IndexMatch object.

---

warehouse/query-core/src/main/java/datawave/query/tracking/ActiveQuery.java
warehouse/query-core/src/main/java/datawave/query/tracking/ActiveQueryLog.java
warehouse/query-core/src/test/java/datawave/query/tracking/ActiveQueryLogTest.java

Change to log4j logging so that we can see the logs on the tservers where this is executed

re #559 Change logging from slf to log4j

---

warehouse/query-core/src/main/java/datawave/query/jexl/DatawaveJexlEngine.java
warehouse/query-core/src/main/java/datawave/query/jexl/JexlASTHelper.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlStringBuildingVisitor.java
warehouse/query-core/src/main/java/datawave/query/language/parser/jexl/JexlNode.java
warehouse/query-core/src/main/java/datawave/query/language/parser/jexl/JexlSelectorNode.java
warehouse/query-core/src/test/java/datawave/query/RegexQueryTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/JexlASTHelperTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java
warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java
warehouse/query-core/src/test/java/datawave/query/testframework/CityDataManager.java
warehouse/query-core/src/test/java/datawave/query/testframework/QueryJexl.java
warehouse/query-core/src/test/resources/input/generic-cities.csv

Updated query parsing to properly handle backslashes in query terms.

---

warehouse/query-core/src/main/java/datawave/query/config/LookupUUIDTune.java

Updated LookupUUIDTune to also enable/disable the UniqueExpressionTermsVisitor.

Updated LookupUUIDTune

---

pom.xml

Update datawave-in-memory-accumulo to 2.0.0

---

warehouse/query-core/src/main/java/datawave/query/planner/ThreadedRangeBundler.java
warehouse/query-core/src/test/java/datawave/query/planner/ThreadedRangeBundlerTest.java

Add unit tests verifying the correctness of ThreadedRangeBundler. In
addition, perform some minor refactoring to both add documentation and
to limit the scope of overly exposed fields.
Fixes #389
If there are additional requirements for this class, let me know and I'll add tests for them.

Add unit tests for ThreadedRangeBundler

---

properties/default.properties
web-services/deploy/application/src/main/wildfly/add-datawave-configuration.cli
web-services/deploy/configuration/src/main/resources/datawave/mapreduce/MapReduceJobs.xml
web-services/map-reduce-embedded/pom.xml
web-services/map-reduce-embedded/src/main/java/datawave/configuration/EmbeddedConfigSource.java
web-services/map-reduce-embedded/src/main/java/datawave/security/system/EmbeddedCallerPrincipalProducer.java
web-services/map-reduce-embedded/src/main/java/datawave/security/system/EmbeddedJSSESecurityDomain.java
web-services/map-reduce-embedded/src/main/java/datawave/security/system/EmbeddedServerPrincipalProducer.java
web-services/map-reduce-embedded/src/main/java/datawave/webservice/common/connection/EmbeddedAccumuloConnectionFactory.java
web-services/map-reduce/pom.xml
web-services/map-reduce/src/main/java/datawave/webservice/mr/MapReduceBean.java
web-services/map-reduce/src/main/java/datawave/webservice/mr/bulkresults/map/BulkResultsFileOutputMapper.java
web-services/map-reduce/src/main/java/datawave/webservice/mr/bulkresults/map/BulkResultsTableOutputMapper.java
web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/BulkResultsJobConfiguration.java
web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java
web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/NeedSecurityDomain.java
web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/OozieJobConfiguration.java
web-services/map-reduce/src/test/resources/datawave/mapreduce/MapReduceJobs.xml
web-services/query/src/main/java/datawave/webservice/query/dashboard/DashboardBean.java

fix #750 Fix BulkResults ( MapReduce API) - broken during Datawave refactoring

fix #750 Fix BulkResults ( MapReduce API) - broken during Datawave refactoring

---

contrib/datawave-quickstart/bin/query.sh

modified:   contrib/datawave-quickstart/bin/query.sh

Fixes #783 - quickstart (query.sh) bugs

---

warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java
warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexFilterIteratorBuilder.java
warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexListIteratorBuilder.java
warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexRangeIteratorBuilder.java
warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexRegexIteratorBuilder.java
warehouse/query-core/src/main/java/datawave/query/iterator/builder/IvaratorBuilder.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java
warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileKeySortedSet.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileSerializableSortedSet.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileSortedSet.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/HdfsBackedSortedSet.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/MultiSetBackedSortedSet.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/RFileKeyInputStream.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/RFileKeyOutputStream.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/SortedSetTempFileHandler.java
warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
warehouse/query-core/src/test/java/datawave/query/util/sortedset/BufferedFileBackedKeySortedSetTest.java
warehouse/query-core/src/test/java/datawave/query/util/sortedset/BufferedFileBackedSortedSetTest.java
warehouse/query-core/src/test/java/datawave/query/util/sortedset/HdfsBackedSortedSetTest.java

* reworked the sorted sets to allow for seeking by using the tailSet method.

fixed #810: efficient sorted set seeking

---

warehouse/query-core/src/main/java/datawave/query/iterator/profile/FinalDocumentTrackingIterator.java
warehouse/query-core/src/test/java/datawave/query/IvaratorYieldingTest.java
warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorTest.java
warehouse/query-core/src/test/java/datawave/query/testframework/QueryLogicTestHarness.java

* Created a test case that recreates the issue.
* Fixed the edge case.

fixes #797: unsorted and yielding do not play well together

---

warehouse/query-core/src/main/java/datawave/query/config/TermFrequencyQueryConfiguration.java
warehouse/query-core/src/main/java/datawave/query/table/parser/TermFrequencyKeyValueFactory.java
warehouse/query-core/src/main/java/datawave/query/tables/term/TermFrequencyQueryTable.java
warehouse/query-core/src/main/java/datawave/query/transformer/TermFrequencyQueryTransformer.java
web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml

* Implements a query logic that returns the tf entries from the shard table.

TermFrequency Query Logic

---

warehouse/query-core/src/main/java/datawave/query/planner/rules/RegexSimplifierTransformRule.java
warehouse/query-core/src/test/java/datawave/query/planner/rules/NodeTransformVisitorTest.java

* Created a NodeTransform to simplify regex expressions for performance reasons

fixes #836: Simplify regex expressions

---

warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownFunction.java
warehouse/query-core/src/main/java/datawave/query/scheduler/PushdownScheduler.java

This reverts commit 9e418e5974eece0958ffbc6b3324fe2250cff3b9.
Conflicts:
contrib/in-memory-accumulo/src/main/java/datawave/accumulo/inmemory/InMemoryTableOperations.java

Revert "Replace code in PushdownFunction with Accumulo API"

---

warehouse/query-core/src/main/java/datawave/query/tables/DedupingIterator.java
warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java
warehouse/query-core/src/test/java/datawave/query/tables/DedupingIteratorTest.java

new config options, and junits added

Fixes #785: fixes for DedupingIterator and UniqueTransform,

---

warehouse/query-core/src/main/java/datawave/query/jexl/lookups/LookupTermsFromRegex.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FixUnfieldedTermsVisitor.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java
warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java

Commits for #833 and #855 were originally reverted due to suspected performance-related problems, but subsequent testing thoroughly disproved that conclusion. Both commits are fine. They are also dandy

Revert revert

---

properties/default.properties
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/EventMapper.java
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoader.java
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/JobObservable.java
warehouse/ingest-core/src/main/java/datawave/ingest/test/StandaloneTaskAttemptContext.java
warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/EventMapperTest.java
warehouse/ingest-scripts/src/main/resources/bin/ingest/map-file-bulk-loader.sh

need confirmation this is the right branch for this.

fixes #923 Add JobObservable and notifications during bulk load and live ingest

---

warehouse/query-core/src/main/java/datawave/query/util/sortedset/BufferedFileBackedSortedSet.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileSortedSet.java
warehouse/query-core/src/test/java/datawave/query/util/sortedset/BufferedFileBackedSortedSetTest.java

* Implemented removeIf on the supper class BufferedFileBackedSortedSet

fixes #907 Implement removeIf on HdfsBackedSortedSet

---

warehouse/query-core/src/main/java/datawave/query/util/sortedset/BufferedFileBackedSortedSet.java
warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileSortedSet.java

Updated the FileSortedSet to allow loading and then unloading filesets that are unchanged

fixes #949: FileSortedSet load/unload

---

warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryModelVisitorTest.java

Verify that QueryModelVisitor does not modify the provided original JEXL
tree, or invalid its lineage.
Part of #968.

Verify QueryModelVisitor does not modify input tree

---

warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FixNegativeNumbersVisitorTest.java

Verify that FixNegativeNumbersVisitor does not modify the provided
original JEXL tree, or invalidate its lineage.
Part of #968

Verify FixNegativeNumbersVisitor does not modify input tree

---

warehouse/query-core/src/test/java/datawave/query/tables/facets/FacetCheckTest.java

Verify that FacetCheck does not modify the provided original JEXL tree,
or invalidate its lineage.
Part of #968

Verify FacetCheck does not modify input tree

---

warehouse/query-core/src/main/java/datawave/core/iterators/TermFrequencyIterator.java
warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetFunction.java
warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
warehouse/query-core/src/test/java/datawave/core/iterators/TermFrequencyIteratorTest.java
warehouse/query-core/src/test/java/datawave/query/data/parsers/DatawaveKeyTest.java
warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java

- TermFrequencyIterator has a smarter seek
- Search space is pruned by fields in the document
- FieldValues moved to TermOffsetPopulator.

Improve TermFrequencyIterator seek

---

warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java
warehouse/query-core/src/test/java/datawave/query/transformer/GroupingTest.java
warehouse/query-core/src/test/java/datawave/query/util/VisibilityWiseGuysIngest.java

Currently, groupby code only compares the value which is breaking when groupby fields have the same value.

Groupby function should group fields based on value/name

---

warehouse/query-core/src/main/java/datawave/query/function/JexlEvaluation.java
warehouse/query-core/src/main/java/datawave/query/function/LimitFields.java
warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
warehouse/query-core/src/main/java/datawave/query/transformer/DocumentTransformerSupport.java
warehouse/query-core/src/test/java/datawave/query/HitsAreAlwaysIncludedCommonalityTokenTest.java
warehouse/query-core/src/test/java/datawave/query/IfThisTestFailsThenHitTermsAreBroken.java
warehouse/query-core/src/test/java/datawave/query/UniqueTest.java
warehouse/query-core/src/test/java/datawave/query/UseOccurrenceToCountInJexlContextTest.java
warehouse/query-core/src/test/java/datawave/query/function/HitsAreAlwaysIncludedTest.java
warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java

Updated the list of checked unique fields to include model mappings and HIT_TERM

re #712: Updated the list of checked unique fields

---

warehouse/query-core/src/main/java/datawave/query/function/JexlEvaluation.java
warehouse/query-core/src/main/java/datawave/query/jexl/DatawaveInterpreter.java
warehouse/query-core/src/test/java/datawave/query/FilterFunctionQueryTest.java
warehouse/query-core/src/test/java/datawave/query/function/JexlEvaluationTest.java

Addresses https://github.com/NationalSecurityAgency/datawave/issues/1073

Fix bug in DatawaveInterpreter that caused incorrect resolution of filter functions

---

warehouse/query-core/src/main/java/datawave/query/iterator/logic/AndIterator.java

rebased to release/version3.2, see #932 for previous discussion

fixes #927 Always move the next highest key in AndIterator

---

pom.xml

fixes #1082: Upgrade datawave-metadata-utils to 1.7

---

warehouse/query-core/src/main/java/datawave/query/jexl/JexlASTHelper.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/EventDataQueryExpressionVisitor.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java
warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FieldToFieldComparisonVisitor.java
warehouse/query-core/src/main/java/datawave/query/metrics/ContentQueryMetricsIngestHelper.java
warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
warehouse/query-core/src/test/java/datawave/query/CompositeFunctionsTest.java
warehouse/query-core/src/test/java/datawave/query/FunctionalSetTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/JexlASTHelperTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/visitors/EventDataQueryExpressionVisitorTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitorTest.java
warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FieldToFieldComparisonVisitorTest.java
warehouse/query-core/src/test/java/datawave/query/util/WiseGuysIngest.java
warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml

I tried to make local/safer changes for the code and the test. Please let me know if anyone has any concerns. Thanks!

fixes #1041 re #1041: TLDEventDataFilter should handle comparing two identifiers

---

warehouse/query-core/src/main/java/datawave/query/iterator/logic/TermFrequencyIndexIterator.java

Backport #1071 to release/version3.1

TermFrequencyIndexIterator builds scan range lazily. (#1071)

---

properties/default.properties
warehouse/ingest-configuration/src/main/resources/config/flag-maker-live.xml
web-services/deploy/application/src/main/wildfly/add-datawave-configuration.cli
web-services/deploy/application/src/main/wildfly/remove-datawave-configuration.cli

Expose the timeout configurations for the live flag maker and the datawave table cache

Expose Configurations

---

warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoFunctions.java
warehouse/query-core/src/main/java/datawave/query/jexl/functions/GeoWaveFunctions.java
warehouse/query-core/src/main/java/datawave/query/jexl/functions/GroupingRequiredFilterFunctions.java
warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctions.java

Add more null checks in JEXL functions to prevent empty fields (value=null) from causing InvocationExceptions from being propagated

Bugfix/issue 887 - Add more null checks in JEXL functions

---

contrib/datawave-quickstart/docker/Dockerfile

Backporting fix for quickstart per Keith's comment on https://github.com/NationalSecurityAgency/datawave/pull/1202

Closes #1184 - Broken quickstart CI job fixed (#1185)

---

warehouse/query-core/src/test/java/datawave/query/language/parser/lucene/TestLuceneQueryParser.java

Re: #874 
- Created test for handing spaces after colon for handling AND and OR queries.

Lucene parsing with space after colon 
