NationalSecurityAgency/datawave

warehouse/core/src/main/java/datawave/data/hash/UID.java, warehouse/ingest-core/src/main/java/datawave/ingest/config/RawRecordContainerImpl.java, warehouse/ingest-core/src/main/java/datawave/ingest/data/RawRecordContainer.java, warehouse/ingest-core/src/main/java/datawave/ingest/input/reader/AbstractEventRecordReader.java, warehouse/ingest-core/src/test/java/datawave/ingest/data/RawRecordContainerImplTest.java, warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/EventMapperTest.java, warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/SimpleRawRecord.java, warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/handler/dateindex/DateIndexDataTypeHandlerTest.java, warehouse/ingest-csv/src/main/java/datawave/ingest/csv/mr/input/CSVReaderBase.java, warehouse/ingest-json/src/main/java/datawave/ingest/json/mr/input/JsonRecordReader.java, warehouse/ingest-json/src/test/java/datawave/ingest/json/config/helper/JsonIngestHelperTest.java, warehouse/ingest-wikipedia/src/main/java/datawave/ingest/wikipedia/WikipediaRecordReader.java, warehouse/query-core/src/test/java/datawave/query/planner/GeoSortedQueryDataTest.java
Avoid multiple UID generation
Remove setRawDataAndGenerateId in lieu of setRawData() and generateId()
Allow for alternate UID implementations
=> fixed #41 Redundant UID generation

web-services/client/src/main/java/datawave/webservice/query/QueryParametersImpl.java, web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java, web-services/query/src/test/java/datawave/webservice/query/runner/QueryExecutorBeanTest.java
It'll be easier to see my changes in the test file if you just view the file as a whole rather than as in-line changes. I refactored a bit to make things less copy-and-pasted by moving the creation of test queries/parameters to helper methods.
I have tried unsuccessfully to get the project to build with tests via the `mvn clean install` command for testing before this PR. Every time I try, it hangs after the `datawave.ingest.mapreduce.partition.BalancedShardPartitionerTest`. However, I have successfully run all tests in the module these changes were made in `datawave-ws-query`. This suggests to me that the issue is actually due to configuration rather than from any changes made.
If anyone has any suggestions for how to fix my VM configurations, that would be appreciated! In the meantime, …
=> Allow for null dates in queries

warehouse/ingest-scripts/src/main/resources/bin/system/start-ingest.sh, warehouse/ingest-scripts/src/main/resources/bin/system/start-metrics-ingest.sh, warehouse/ingest-scripts/src/main/resources/bin/system/stop-ingest.sh, warehouse/ingest-scripts/src/main/resources/bin/system/stop-metrics-ingest.sh
Previous version of these scripts used the redirection arguments `-o /tmp/stdout` and `-e /tmp/stderr` for `pssh` when executing these commands. In moving to `pdsh` this was immitated by redirecting to `/tmp/stderr` and `/tmp/stdout`. However, since the previous command version actually created `/tmp/stdout` and `/tmp/stderr` as folders containing the `stdout` and `stderr` of each node contacted, the `pdsh` version of the command fails since it tries to write to a folder instead of a file.
This is a temporary fix that will be made better in the future by utilizing [`dshbak`](https://linux.die.net/man/1/dshbak) to write out results by node for debugging purposes.
=> Remove redirects to /tmp/stdout and /tmp/stderr

warehouse/core/src/main/java/datawave/util/AccumuloCounterSource.java, warehouse/core/src/main/java/datawave/util/cli/PasswordConverter.java, warehouse/core/src/test/java/datawave/util/cli/PasswordConverterTest.java, warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoader.java, warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java, warehouse/ingest-core/src/main/java/datawave/ingest/util/AccumuloCliOptions.java, warehouse/ingest-core/src/main/java/datawave/ingest/util/GenerateEdgeKeyVersionCache.java, warehouse/ingest-core/src/main/java/datawave/ingest/util/GenerateMultipleNumShardsCacheFile.java, warehouse/ingest-core/src/main/java/datawave/ingest/util/GenerateShardSplits.java, warehouse/ingest-core/src/main/java/datawave/ingest/util/GenerateSplitsFile.java, warehouse/query-core/src/main/java/datawave/query/cardinality/CardinalityScanner.java
Created PasswordConverter class to allow users to specify passwords
using an env: prefix.  This will indicate that an ENVIRONMENT variable
should be used to obtain the password.
This is useful in order to prevent passwords from showing up in the process list
Updated some core classes to make use of this convention.
=> Added PasswordConverter to allow passwords from environment

warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexFilterIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexListIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexRangeIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexRegexIteratorJexl.java, warehouse/query-core/src/main/java/datawave/query/ancestor/AncestorIndexIterator.java, warehouse/query-core/src/main/java/datawave/query/ancestor/AncestorIndexIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/CardinalityIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexFilterIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexListIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexRangeIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexRegexIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/logic/IndexIterator.java, warehouse/query-core/src/main/java/datawave/query/tld/TLDIndexIterator.java, warehouse/query-core/src/main/java/datawave/query/tld/TLDIndexIteratorBuilder.java
modified:   warehouse/query-core/src/main/java/datawave/query/ancestor/AncestorIndexIterator.java
modified:   warehouse/query-core/src/main/java/datawave/query/ancestor/AncestorIndexIteratorBuilder.java
modified:   warehouse/query-core/src/main/java/datawave/query/iterator/builder/CardinalityIteratorBuilder.java
modified:   warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexIteratorBuilder.java
modified:   warehouse/query-core/src/main/java/datawave/query/iterator/logic/IndexIterator.java
modified:   warehouse/query-core/src/main/java/datawave/query/tld/TLDIndexIterator.java
modified:   warehouse/query-core/src/main/java/datawave/query/tld/TLDIndexIteratorBuilder.java
=> use builder pattern for IndexIterator and Ivarator classes

web-services/client/src/main/java/datawave/webservice/result/QueryLogicResponse.java
I changed the URL path from /DataWave/doc/javadocs instead of /DataWave/doc/apidocs/jaxbdocs/ in order to fix some broken links on the Deployed Query Logic page.
=> Fixing broken URLs per issue #167

warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java, warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsDescriptor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitor.java, warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/JexlTreeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/Options.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Options.java, warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java, warehouse/query-core/src/main/java/datawave/query/planner/QueryOptionsSwitch.java, warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java, warehouse/query-core/src/test/java/datawave/query/CompositeFunctionsTest.java, warehouse/query-core/src/test/java/datawave/query/function/HitsAreAlwaysIncludedTest.java
modified:   warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
modified:   warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsDescriptor.java
new file:   warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryOptionsFromQueryVisitor.java
modified:   warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
new file:   warehouse/query-core/src/main/java/datawave/query/planner/QueryOptionsSwitch.java
modified:   warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
modified:   warehouse/query-core/src/test/java/datawave/query/CompositeFunctionsTest.java
modified: …
=> add function to carry queryOptions into the ShardQueryConfiguration

warehouse/core/src/main/java/datawave/edge/util/EdgeKeyUtil.java, warehouse/query-core/src/main/java/datawave/query/edge/DefaultExtendedEdgeQueryLogic.java, warehouse/query-core/src/main/java/datawave/query/tables/edge/contexts/VisitationContext.java, warehouse/query-core/src/test/java/datawave/query/tables/edge/TestEdge.java
Changes to Edge Utility code to correctly escape search terms when building ranges. This is needed to match the same encoding scheme that is used on ingest for the edge table. Without this change search terms that include special characters may result in invalid search ranges.
=> Fixed edge query range encoding

warehouse/core/src/main/java/datawave/ingest/util/cache/watch/FileRuleWatcher.java
Previously used this.getClass.getResource() to look up file.  This will
not necessarily resolve files with hdfs:// prefixes, which results in an
unintended IllegalArgumentException
=> Fix for FileRuleWatcher where path to file in hdfs not loaded correctly

warehouse/core/src/main/java/datawave/ingest/util/cache/watch/FileRuleWatcher.java, warehouse/core/src/test/java/datawave/ingest/util/cache/watch/FileRuleFieldMergeTest.java, warehouse/core/src/test/java/datawave/ingest/util/cache/watch/FileRuleLoadContentsMergeFiltersTest.java, warehouse/core/src/test/resources/test-customized-data-type.xml, warehouse/core/src/test/resources/test-customized-field.xml, warehouse/core/src/test/resources/test-customized-rules.xml, warehouse/core/src/test/resources/test-root-field.xml
Fix now works with hdfs:/// and classpath based URLs.  Verified unit tests are passing once again.
=> File rule watcher load path fix

warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/EventMapper.java, warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/EventMapperTest.java, warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/SimpleRawRecord.java
Some RecordReaders may generate Events with null raw data fields because they pass data to their handlers in other ways. Fix the EventMapper so that it can properly handle the case where an Event's raw data field is null.
=> Fix NullPointerException in EventMapper when Event rawData field is null

warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/StandardAnalyzer.java, warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/StandardTokenizer.java, warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/RegexpQueryNodeBuilder.java, warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java
@keith-ratcliffe  here are some changes to #238 that bring the `StandardTokenizer` / `StandardAnalyzer` in line with some of the changes to the equivalent classes in the Lucene codebase.
=> Re #234 Tweaks to lucene upgrade PR

warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java, warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java
This change is to ensure we can handle lower case field names for tokenized and non-tokenized fields.
=> Case independent token field

web-services/query/src/main/java/datawave/webservice/query/logic/QueryLogic.java, web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java, web-services/query/src/test/java/datawave/webservice/query/runner/ExtendedQueryExecutorBeanTest.java
The way getting a `QueryLogic`'s response class works right now makes the assumption that the `QueryLogic` doesn't need to be initialized in order to have a successful call on `getTransformer`. Since the call fails on several logics, the `listQueryLogic` page has several "unknown" response classes.
This fix enables `QueryLogic`s to Override the default implementation of the new method `getResponseClass`. This way the logics that work with this original implementation are not affected and new logics that would need to implement an override to this method could do so and avoid always having an "unknown" response class.
=> Let QueryLogic determine its response class

warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/RegexpQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/parser/jexl/LuceneToJexlQueryParser.java, warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java, warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java
- Reworks CustomAnalyzerQueryNodeProcessor to handle the various
cases we will encounter when tokenizing QueryNodes: single terms,
phrases and phrases with slop.
- Adds unit tests to cover these cases
- Removes stray System.out from RegexpQueryNodeBuilder
- Adjusts some configuration parameter names for CustomAnalyzerQueryNodeProcessor
for clarity.
=> Fixes #257: UnsupportedOperationException on unfielded SlopQueryNode

warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java, warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java
This Slop Query Parsing fix in #257 had an implementation bug that wasn't caught because the unit test that would have caught it was set to Ignore. Removed Ignore, fixed the test and fixed the underlying implementation issue.
=> Fixes issue introduced in #257 and test that would have caught it

warehouse/ingest-scripts/src/main/resources/bin/ingest/cleanup-server.py
Pulling in fix from [https://github.com/NationalSecurityAgency/datawave-old/issues/273](https://github.com/NationalSecurityAgency/datawave-old/issues/273)
"`cleanup_server.py` will clear all logs out of directory if the flag file has too few dots"
=> Fix if cleanup_server.py if the flag file has too few dots

pom.xml
It looks like this wildfly-undertow dependency is declared in the dependencyManagement section, but is never used as a dependency in any module, nor a transitive dependency of any declared dependencies. So, this section of the pom gets ignored in the build, and should be removed, to avoid triggering false positives when GitHub automatically analyses projects for vulnerable declared dependencies.
=> Remove unused managed dependency

warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardedTableMapFile.java, warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/job/ShardedTableMapFileTest.java
New shardedMap.max.tablets.per.shard config property will allow a maximum
number of shards per tablet.  This is useful for the case that there
are more shards then there are tservers on the system. We still want to be
balanced as much as possible, but some can be on more then one up to max.
=> Modified Shard Balance check to allow multiple per tserver

warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java, warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsDescriptor.java, warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctions.java, warehouse/query-core/src/main/java/datawave/query/language/builder/jexl/JexlTreeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/FunctionQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/AbstractEvaluationPhaseFunction.java, warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/Exclude.java, warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/GroupBy.java, warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/Text.java, warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/Unique.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/AbstractEvaluationPhaseFunction.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Exclude.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/GroupBy.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Text.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Unique.java, warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java, warehouse/query-core/src/test/java/datawave/query/FilterFieldsQueryTest.java, warehouse/query-core/src/test/java/datawave/query/LuceneQueryTest.java, warehouse/query-core/src/test/java/datawave/query/TextFunctionQueryTest.java, warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlParser.java, warehouse/query-core/src/test/java/datawave/query/language/parser/jexl/TestLuceneToJexlQueryParser.java, warehouse/query-core/src/test/java/datawave/query/language/parser/lucene/TestLuceneQueryParser.java, warehouse/query-core/src/test/java/datawave/query/testframework/AbstractFunctionalQuery.java, warehouse/query-core/src/test/resources/datawave/query/EventQueryLogicFactory.xml, warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml, web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml
Added a #TEXT (filter.includeText) function which takes the same syntax as #INCLUDE or #EXCLUDE.
Added a shortcut of #TEXT(x) which implies #TEXT(_ANYFIELD_,x).  Same for #INCLUDE and #EXCLUDE.
Modified planner to expand function index queries before expanding anyfield expressions to #TEXT(x).
Added test cases for lucene and jexl expansions as well as functional tests.
=> fixes #309: #TEXT function

warehouse/query-core/src/main/java/datawave/query/Constants.java, warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/AllTermsIndexedVisitor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FixUnfieldedTermsVisitor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ParallelIndexExpansion.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/PushdownLargeFieldedListsVisitor.java, warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java, warehouse/query-core/src/main/java/datawave/query/planner/FacetedQueryPlanner.java, warehouse/query-core/src/main/java/datawave/query/planner/IndexQueryPlanner.java, warehouse/query-core/src/main/java/datawave/query/planner/pushdown/CostEstimator.java, warehouse/query-core/src/main/java/datawave/query/tables/facets/FacetCheck.java, warehouse/query-core/src/test/java/datawave/query/AnyFieldQueryTest.java
Changes non-expandable un-fielded terms to _NOFIELD_ instead of throwing errors when not nested in an OR.
=> fixes #342: Unfielded NOTs dropped from query plan

pom.xml, services/base-rest-responses/src/main/java/datawave/webservice/query/exception/DatawaveErrorCode.java, warehouse/query-core/src/main/java/datawave/query/QueryParameters.java, warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java, warehouse/query-core/src/main/java/datawave/query/discovery/DiscoveryLogic.java, warehouse/query-core/src/main/java/datawave/query/tables/PartitionedQueryTable.java, warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java, warehouse/query-core/src/main/java/datawave/query/tables/chained/ChainedQueryTable.java, warehouse/query-core/src/main/java/datawave/query/tables/edge/EdgeQueryLogic.java, warehouse/query-core/src/main/java/datawave/webservice/modification/MutableMetadataHandler.java, warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java, web-services/client/src/main/java/datawave/webservice/query/Query.java, web-services/client/src/main/java/datawave/webservice/query/QueryImpl.java, web-services/client/src/main/java/datawave/webservice/query/QueryParameters.java, web-services/client/src/main/java/datawave/webservice/query/QueryParametersImpl.java, web-services/query/src/main/java/datawave/webservice/query/configuration/GenericQueryConfiguration.java, web-services/query/src/main/java/datawave/webservice/query/dashboard/DashboardQuery.java, web-services/query/src/main/java/datawave/webservice/query/logic/BaseQueryLogic.java, web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutor.java, web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java, web-services/query/src/main/java/datawave/webservice/query/runner/RunningQuery.java, web-services/query/src/test/java/datawave/webservice/query/configuration/TestGenericQueryConfiguration.java, web-services/query/src/test/java/datawave/webservice/query/runner/ExtendedQueryExecutorBeanTest.java, web-services/query/src/test/java/datawave/webservice/query/runner/ExtendedRunningQueryTest.java
The goal is to allow a PrivilegedUser to be able to override the maxResults setting with values larger than that configured on a query logic.  This involved moving the processing of the max.results.override handling out of the query logics and into the QueryExecutorBean and RunningQuery classes.
=> re #345: Moving max results override out of query logics

web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java, web-services/query/src/test/java/datawave/webservice/query/runner/QueryExecutorBeanTest.java
Added a cache of closed ids to allow subsequent close requests to succeed
=> fixes #384: allow multiple close requests

warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/BulkIngestMapFileLoader.java, warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java, warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/reduce/AggregatingReducer.java, warehouse/metrics-core/src/main/java/datawave/metrics/analytic/FileByteSummaryLoader.java, warehouse/query-core/src/main/java/datawave/mr/bulk/MultiRfileInputformat.java, warehouse/query-core/src/main/java/datawave/mr/bulk/RfileScanner.java, warehouse/query-core/src/main/java/datawave/query/metrics/AccumuloRecordWriter.java, warehouse/query-core/src/main/java/datawave/query/tables/ScannerFactory.java, web-services/accumulo/src/main/java/datawave/webservice/operations/admin/UpdateBean.java
* Replace IterInfo with IteratorSetting in IngestJob
* Use the Accumulo API IteratorSetting instead of internal thrift
IterInfo class
* Replace old accumulo code in AggregatingReducer
* Replace Constants.NO_AUTHS with Authorizations.EMPTY
* Replace Tables class with Accumulo API
Since my other request (#321) was already approved I didn't want to push more changes to that branch. These changes are similar in that they should be safe and will work with Accumulo versions 1.8, 1.9 and 2.0.
=> Replace use of Accumulo internals with 1.8 API

warehouse/ingest-scripts/src/main/resources/bin/metrics/analytic.sh
analytic.sh doesn't use ingest-libs.sh and instead builds it's own classpath. adding a missing jar.
=> Added missing jar to analytic.sh

warehouse/query-core/src/test/java/datawave/query/IfThisTestFailsThenHitTermsAreBroken.java, warehouse/query-core/src/test/java/datawave/query/QueryTestTableHelper.java, warehouse/query-core/src/test/java/datawave/query/UseOccurrenceToCountInJexlContextTest.java, warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml, web-services/client/src/main/java/datawave/webservice/query/metric/BaseQueryMetric.java, web-services/deploy/configuration/src/main/resources/datawave/query/EdgeQueryLogicFactory.xml, web-services/deploy/configuration/src/main/resources/datawave/query/QueryLogicFactory.xml, web-services/query/src/main/java/datawave/webservice/query/configuration/GenericQueryConfiguration.java, web-services/query/src/main/java/datawave/webservice/query/logic/BaseQueryLogic.java, web-services/query/src/main/java/datawave/webservice/query/logic/QueryLogic.java, web-services/query/src/main/java/datawave/webservice/query/runner/RunningQuery.java, web-services/query/src/test/java/datawave/webservice/query/configuration/GenericQueryConfigurationMockTest.java, web-services/query/src/test/java/datawave/webservice/query/configuration/TestBaseQueryLogic.java, web-services/query/src/test/java/datawave/webservice/query/logic/QueryLogicFactoryBeanTest.java, web-services/query/src/test/java/datawave/webservice/query/logic/TestQueryLogic.java, web-services/query/src/test/java/datawave/webservice/query/runner/ExtendedRunningQueryTest.java, web-services/query/src/test/resources/TestQueryLogicFactory.xml, web-services/query/src/test/resources/TestQueryLogicFactoryWithAuditType.xml
Deprecate the maxRowsToScan feature and replace with a maxWork feature.
=> fixex #428: Deprecate maxRowsToScan, add maxWork

warehouse/ingest-core/src/main/java/datawave/iterators/PropogatingIterator.java, warehouse/ingest-core/src/test/java/datawave/iterators/PropogatingIteratorSeekTest.java, warehouse/ingest-core/src/test/java/datawave/iterators/PropogatingIteratorTest.java
PropogatingIterator makes an extra next() call, even for keys that do not require aggregation.  This change delays the call to next() and in some use cases prevents the need to call next() at all.  This can save a substantial amount of time for data that is being skipped by a filter.
=> Avoid read ahead for non-aggregating column families

warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/MetadataTableSplitsCacheStatus.java
If IOException is thrown in 'try' block then just return false from isCacheValid without calling methods on the what will be null 'fileStatus' object which will cause the NullPointerException.
=> Fixes #248 - faulty logic in MetadataTableSplitsCacheStatus causes NPE

warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardedTableMapFile.java
This fix prevents TabletId's with null endrows from populating the splitlocation map.  This is effectively what the old code did but it it would would retry until the number of retries ran out in the failure of the writeSplitsFile function.   I try to filter out the tabletId with the null end row with a Java 8 lambda but I am getting an UnsupportedOperationError which leads me to think that the Java version in my IDE is not the same as what DataWave is using.  On line 360 I had to do an ugly old school iteration and testing of the tabletId for the null end row because the removif lambda doensn't work and putting the test in the tabletIds.forEach lambda makes the code unreadable.
=> Fixes #391 - ShardedTableMapFile NPE for every table

contrib/datawave-quickstart/bin/services/datawave/ingest-examples/runFMLoadTest.sh, contrib/datawave-quickstart/bin/services/datawave/ingest-examples/tvmaze-flagmaker.sh, warehouse/ingest-core/src/main/java/datawave/util/flag/FlagEntryMover.java, warehouse/ingest-core/src/main/java/datawave/util/flag/FlagMaker.java, warehouse/ingest-core/src/main/java/datawave/util/flag/FlagMetrics.java, warehouse/ingest-core/src/main/java/datawave/util/flag/InputFile.java, warehouse/ingest-core/src/main/java/datawave/util/flag/SimpleMover.java, warehouse/ingest-core/src/main/java/datawave/util/flag/config/FlagMakerConfig.java, warehouse/ingest-core/src/main/java/datawave/util/flag/processor/DateUtils.java, warehouse/ingest-core/src/test/java/datawave/util/flag/AbstractFlagConfig.java, warehouse/ingest-core/src/test/java/datawave/util/flag/FlagEntryMoverTest.java, warehouse/ingest-core/src/test/java/datawave/util/flag/FlagMakerLoad.java, warehouse/ingest-core/src/test/java/datawave/util/flag/FlagMakerTest.java, warehouse/ingest-core/src/test/java/datawave/util/flag/IngestConfig.java, warehouse/ingest-core/src/test/java/datawave/util/flag/IngestWorker.java, warehouse/ingest-core/src/test/java/datawave/util/flag/InputFileTest.java, warehouse/ingest-core/src/test/java/datawave/util/flag/SimpleMoverTest.java, warehouse/ingest-core/src/test/resources/FlagLoadConfig.json, warehouse/ingest-core/src/test/resources/TestFlagMakerConfig.xml, warehouse/ingest-core/src/test/resources/log4j.properties
The following modifications were made to the flag maker:
- Unused static and instance variables were removed.
- Validation of the configuration data was moved to the FlagMakerConfig class.
- The class FlagEntryMover and SimpleMover have been introduced to manage the state of an input file.
- The class FlagMetrics has been introduced to write flag metrics.
- Unit test classes have been added for the new classes.
- A test class and associated scripts have been added for system/load/stress testing for the flag maker. The system test can be used to inject input files into the flag maker for processing and will result in the data being populated into Accumulo.
=> Flag maker updates to handle race condition and duplicate input files

warehouse/query-core/src/test/java/datawave/query/cardinality/TestCardinalityWithQuery.java, warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java, warehouse/query-core/src/test/java/datawave/query/tables/IndexQueryLogicTest.java, warehouse/query-core/src/test/java/datawave/query/testframework/AbstractFunctionalQuery.java
in a few tests to prevent random test failures.  This was recommended on the Junit4 thread to fix this temporary issue.  This code change has been tested on a single machine and the code builds with:
'mvn -Pdev -Ddeploy -Dtar  clean install'
=> Replaced use of Junit TemporaryFolder with Files.createTempDirectory

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ParallelIndexExpansion.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TreeFlatteningRebuildingVisitor.java, warehouse/query-core/src/test/java/datawave/query/AnyFieldQueryTest.java, warehouse/query-core/src/test/java/datawave/query/LuceneQueryTest.java
This also required updating the tree flattening rebuilding visitor to combine a marked node with other anded sibling nodes as long as none of them are wrapped.
=> Update ASTEvaluationOnly to properly prevent ranges and regex from expanding

pom.xml
Used ```mvn versions:display-plugin-updates``` to find these updates.  This should help with migration to Java 11.  See #510
=> Update bunch of maven plugins

warehouse/ingest-scripts/src/main/resources/bin/system/cleanup_old_pdsh_logs.sh, warehouse/ingest-scripts/src/main/resources/bin/util/cleanup_old_files_util.sh
[PR 184](https://github.com/NationalSecurityAgency/datawave/pull/184) will generate logs via `pdsh` commands that need to be cleaned up on clusters. This added utility will remove `pdsh` logs older than 7 days in order to keep the system clean and ensure there is enough time to investigate `pdsh` command errors.
=> Add utility to clean up logs produced by pdsh dshbak logging

warehouse/query-core/src/main/java/datawave/query/jexl/DatawaveInterpreter.java, warehouse/query-core/src/test/java/datawave/query/jexl/DatawaveInterpreterTest.java
This should stop the stack overflows caused by recursively traversing or nodes composed of too many terms.
=> Updated the datawave interpreter to use iterative traversal for or nodes

docs/pom.xml
Add datawave-ws-model as a dependency for datawave-docs so that the
source files (including ModelBean) will be read and included by the
enunciate plugin.
Fixes #498
=> Include ModelBean in API documentation

services/audit-service/src/main/java/datawave/microservice/audit/AuditController.java
Throw a RuntimeException in AuditController.sendMessage() when
messageChannel.send returns false in order to prevent 2xx response
codes.
Fixes #218
=> Clean up boolean logic in AuditController

contrib/datawave-quickstart/docker/Dockerfile
Updated dependency to include gettext for envsubst.
Fixes #535
=> Fixes #535 - Quickstart docker image errors during ingest

services/dictionary-api/src/main/java/datawave/webservice/results/datadictionary/DefaultDataDictionary.java
So the solution is to say that a Field Name in the Metadata  table is normalize if it has an underlying datatype which was what was decided in the issue #479 
I had to make pom.xml changes to get this to see my code modification to actually get used in the services project and I can push those changes if required.  The SNAPSHOT jar for dictionary-api was not being used.
This solution has been tested and stepped through in a debugger.
=> Fixes #479 - Populate normalization column in the data dictionary

warehouse/core/src/main/java/datawave/iterators/filter/AgeOffConfigParams.java, warehouse/core/src/main/java/datawave/iterators/filter/ageoff/FieldAgeOffFilter.java, warehouse/core/src/test/java/datawave/iterators/filter/ageoff/FieldAgeOffFilterTest.java
Implements ability to exclude event data from a field age-off rule.
Specify the following to enable capability on a rule:
```
excludeData=event
```
=> Fixes #556 - Age-off filter event data exclusion

warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/IteratorThreadPoolManager.java, warehouse/query-core/src/main/java/datawave/query/iterator/NestedIterator.java, warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java, warehouse/query-core/src/main/java/datawave/query/iterator/SeekableNestedIterator.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/AbstractIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexFilterIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexListIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexRangeIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/IndexRegexIteratorBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/builder/TermFrequencyIndexBuilder.java, warehouse/query-core/src/main/java/datawave/query/iterator/logic/IndexIteratorBridge.java, warehouse/query-core/src/main/java/datawave/query/iterator/pipeline/PipelineIterator.java, warehouse/query-core/src/main/java/datawave/query/iterator/profile/EvaluationTrackingNestedIterator.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java, warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IteratorBuildingVisitorTest.java
* Pass IteratorEnvironment to the thread pool manager, allowing removal
of ServerConfigurationFactory and HdfsZooInstance in support of #533
* Added IteratorEnvironment to NestedIterator and many places in builders
* Removed unused threadpool objects in IteratorThreadPoolManager
=> Pass down IterEnvironment to IteratorThreadPoolManager

warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/EventMapper.java, warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/EventMapperTest.java, warehouse/ingest-core/src/test/java/datawave/ingest/mapreduce/SimpleRawRecord.java
Exclude error events with timestamp less than discard interval from
being dropped.  An event may be in error when the timestamp is unable
to be parsed.  We don't want to drop these events, but send them to
the error tables.
=> Added exclusion for error events being dropped (#594)

warehouse/query-core/src/main/java/datawave/query/tables/ResourceQueue.java
- final because this class shouldn't be used as an extension point
- cleaned up constructors to enable final fields
- Generics for `GenericObjectPool`
- Eliminated some redundant fields
- `ScannerQueueFactory` now a static nested class (also private final, not to be resued.)
- Removed unused Queue from ScannerQueueFactory.
- Renamed ScannerQueueFactory to AccumuloResourceFactory
- Cleaned up some unnecessary auto-generated method comments.
=> Cleanup of ResourceQueue code.

pom.xml, services/spring-boot-starter-datawave/pom.xml, warehouse/assemble/datawave/pom.xml, warehouse/assemble/datawave/src/main/assembly/dist.xml, warehouse/pom.xml, warehouse/query-core/pom.xml, warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java, warehouse/query-core/src/main/java/datawave/query/tracking/ActiveQuery.java, warehouse/query-core/src/main/java/datawave/query/tracking/ActiveQueryLog.java, warehouse/query-core/src/main/java/datawave/query/tracking/ActiveQuerySnapshot.java, warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java, warehouse/query-core/src/test/java/datawave/query/tracking/ActiveQueryLogTest.java
We want a way to see in the logs which queries are putting a load on a specific tserver.
Example logging output:
[GAPZW-47TWB-TUDP7-W7JHA] (tot/cur) 4123/3130 (call num/max/avg/min) seek=2/6/4/3 next=11/1/0/0 (lastDoc bytes/sources/seek/next) 352/1/4/22
The frame of reference is successive seek and next calls on a specific tserver for the same queryId
[query_id] 
total_call_time/current_call_time 
numSeeks/maxMsec/avgMsec/minMsec 
numNexts/maxMsec/avgMsec/minMsec lastDocReturnedSizeButes/numSources/numSourceSeeks/numSourceNexts
- Query records that have not been accessed in maxIdle time will be dropped (configurable)
- The timer in ActiveQueryLog will print this message at the DEBUG level for each query that is in a call (seek or next) at a configurable period.
- The max/avg/min …
=> Re #559 Track active queries in the QueryIterator

.github/workflows/tests.yml, README.md
We have access to GitHub actions which might be a viable CI replacement for the private GitLab repo that we are currently using.
=> Add GitHub action workflow to run tests.

warehouse/ingest-core/src/main/java/datawave/ingest/table/config/AbstractTableConfigHelper.java
* Replace reflection code that was making multiple guesses at an
internal Accumulo method with a copy of the actual method
The IteratorUtil method was moved in Accumulo 2.0.  The one here I copied from 1.9
https://github.com/apache/accumulo/blob/1.9/core/src/main/java/org/apache/accumulo/core/iterators/IteratorUtil.java#L124
=> Replace reflection code with actual method from Accumulo

pom.xml
According to [this](https://github.com/cloudera/zookeeper/commits/cdh6.3.1), the specified version of zookeeper fixes ZOOKEEPER-1392 which fixes the CVE.
=> Update zookeeper to version fixing CVE-2019-0201

warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexFilterIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexListIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexRangeIteratorJexl.java, warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexRegexIteratorJexl.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FixUnfieldedTermsVisitor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IvaratorRequiredVisitor.java, warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java, warehouse/query-core/src/main/java/datawave/query/tables/async/event/VisitorFunction.java, warehouse/query-core/src/test/java/datawave/query/ExpansionThresholdQueryTest.java, warehouse/query-core/src/test/java/datawave/query/MaxExpansionRegexQueryTest.java, warehouse/query-core/src/test/java/datawave/query/cardinality/TestCardinalityWithQuery.java, warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java, warehouse/query-core/src/test/java/datawave/query/testframework/AbstractFunctionalQuery.java
This one fixes the MaxExpansionRegexQueryTest and resulted in fixing #156 as well.
* Updated to use google Files to create temporary directories (avoid known bug in nio Files temporary dir creation)
* Updating planner to correctly fail when attempting to ivarator when not configured.
* Fixed to allow ivarating against _ANYFIELD_ expressions (#156)
=> re #637: periodic test failures

warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java, warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorTest.java
Two main changes
line 943: check that collection is empty prior to adding (no longer blindly add)
line 1379: assign the results of a string building operation
Other changes are spelling touchups.
=> Touching up QueryIterator.

warehouse/query-core/src/main/java/datawave/core/iterators/DatawaveFieldIndexCachingIteratorJexl.java, warehouse/query-core/src/main/java/datawave/query/util/sortedset/BufferedFileBackedSortedSet.java, warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileKeySortedSet.java, warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileSerializableSortedSet.java, warehouse/query-core/src/main/java/datawave/query/util/sortedset/FileSortedSet.java, warehouse/query-core/src/main/java/datawave/query/util/sortedset/HdfsBackedSortedSet.java, warehouse/query-core/src/test/java/datawave/query/util/sortedset/BufferedFileBackedKeySortedSetTest.java
This allows extending the implementation to use a Writable such as the
accumulo Key object.  Updated the ivarator to use sets of Key objects
instead of sets of KeyValueSerializable object avoiding unnecessary object
creations.
=> Refactored the FileSortedSet to avoid dependency on java Serializable.

warehouse/query-core/src/main/java/datawave/query/config/LookupUUIDTune.java, warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java, warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java, warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java, warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
Push the configuration for the UniqueExpressionTermsVisitor down to the logic level vs. the DefaultQueryPlanner level.
=> Better way to configure unique terms within an expression

contrib/datawave-quickstart/bin/services/hadoop/bootstrap.sh
- Hadoop 2.6 doesn't support `mapred --daemon` but uses `mr-jobhistory-daemon.sh` instead.
=> Fix historyserver startup in quickstart

pom.xml
. Building from an empty maven repo also required a version of hibernate that did not use the jta 1.0.1B jar
=> Closes #805 - updated to point to osgeo instead of boundless

warehouse/ingest-core/src/main/java/datawave/IdentityDataType.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandCompositeTermsTest.java
...to avoid build failures in VSCode.
Some commentary: These are all changes to the way generics were managed and thus have implications to compile time as opposed to runtime. IntelliJ and even `javac` as we execute from maven don't care about these, but the syntax/language engine in VSCode does.
In fact, upon analysis, this seems that each of these implementations differ in how they handle a non-parameterized type, e.g: `datawave.data.type.Type` vs. a wildcard parameterized type `datawave.data.type.Type<?>`. 
The case in the mock for `ExpandCompositeTermsTest` is especially interesting because of the use of `Object` in the `compareTo` method. This doesn't adhere to either of the parameter constraints established in `BaseType`, that the templated object be `Comparable` or `Serializable`. …
=> Non-functional tweaks to generics usage

contrib/datawave-quickstart/bin/common.sh, contrib/datawave-quickstart/bin/services/accumulo/bootstrap.sh, contrib/datawave-quickstart/bin/services/datawave/bootstrap-ingest.sh, contrib/datawave-quickstart/bin/services/datawave/bootstrap-web.sh, contrib/datawave-quickstart/bin/services/datawave/bootstrap.sh, contrib/datawave-quickstart/bin/services/hadoop/bootstrap.sh, contrib/datawave-quickstart/bin/services/maven/bootstrap.sh
Added new `[all|servicename]DisplayBinaryInfo` method that will print out the tarball names configured for each service along with the local tarball name, if it's already been downloaded/built
Also, `allInstall` will now print out the tarball info and prompt user with a WARN msg, if a local binary is found that doesn't match the configured source binary (i.e., the associated *_DIST_URI value)
E.g.,...
```
$ allInstall
=========================================================
Binary info for maven
Source: http://mirror.cogentco.com/pub/apache/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
Local: /dev/datawave/contrib/datawave-quickstart/bin/services/maven/apache-maven-3.5.4-bin.tar.gz
=========================================================
Binary info for hadoop
Source: …
```
=> Closes #794: Display/verify quickstart tarballs prior to installation

warehouse/ingest-core/src/main/java/datawave/util/flag/FlagMaker.java
- Addresses issue where a lease exception when writing metrics could
result in flag maker death due to upward-thrown LeaseExpiredException/IOException.
- Needs further investigation/refactoring, but this should address the immediate issue.
=> Failure to write FlagMaker metrics should not be fatal.

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexFunctionVisitor.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/RegexFunctionVisitorTest.java
Add asserts to tests for RegexFunctionVisitor to verify that it returns
a query tree with valid lineage.
Part of #880.
=> Verify lineage for RegexFunctionVisitor

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTerms.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryModelVisitor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java
Updated to not assume flattened ASTAndNode subtree will return an ASTAndNode
=> fixes #973: Assumed ASTAndNode returned from flatten tree

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ValidPatternVisitor.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ValidPatternVisitorTest.java
Backport fix for valid pattern visitor to 2.9, original feature was merged into master.
* ValidPatternVisitor now checks #INCLUDE and #EXCLUDE functions.
* Address PR comments.
* Address PR comments.
Co-authored-by: Brian Loss <brianloss@gmail.com>
Co-authored-by: Ivan Bella <ivan@bella.name>
=> ValidPatternVisitor now checks #INCLUDE and #EXCLUDE functions. (#787)

warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IsNotNullIntentVisitorTest.java
Verify that IsNotNullIntentVisitor does not modify the provided original
JEXL tree, or invalidate its lineage.
Part of #968
=> Verify IsNotNullIntentVisitor does not modifiy input

warehouse/query-core/src/test/java/datawave/query/jexl/visitors/GeoWavePruningVisitorTest.java
Verify that GeoWavePruningVisitor does not modify the provided original
JEXL tree, or invalidate its lineage.
Part of #968
=> Verify GeoWavePruningVisitor does not modify input tree

warehouse/query-core/src/test/java/datawave/query/jexl/visitors/DateIndexCleanupVisitorTest.java
Verify that DateIndexCleanupVisitor does not modify the provided
original tree, or invalidate its lineage.
Part of #968
=> Verify DateIndexCleanupVisitor does not modify input tree

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BooleanOptimizationRebuildingVisitor.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/BooleanOptimizationRebuildingVisitorTest.java
Fix BooleanOptimizationRebuildingVisitor so that it does not modify the
original input JEXL tree, and verify that it maintains a valid lineage.
Part of #968
=> Do not modify input tree in BooleanOptimizationRebuildingVisitor

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RangeCoalescingVisitor.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/RangeCoalescingVisitorTest.java
Fix RangeCoalescingVisitor so that it does not modify the original input
JEXL tree, and verify that it maintains a valid lineage.
Part of #968
=> Do not modify input tree in RangeCoalescingVisitor

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexFunctionVisitor.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/RegexFunctionVisitorTest.java
Fix RegexFunctionVisitor so that it does not modify the original input
JEXL tree, and verify that it maintains a valid lineage.
Part of #968
=> Do not modify input tree in RegexFunctionVisitor

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExpandCompositeTerms.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FunctionIndexQueryExpansionVisitor.java, warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandCompositeTermsTest.java
Ensure that ExpandCompositeTerms returns a JEXL tree with a valid
lineage, and ensure that it does not modify the original input JEXL
tree.
Part of #880 and #968
=> Fix lineage for ExpandCompositeTerms

web-services/common/src/main/java/datawave/configuration/spring/SpringCDIExtension.java, web-services/map-reduce-embedded/pom.xml, web-services/map-reduce-embedded/src/main/java/datawave/security/system/EmbeddedCallerPrincipalProducer.java, web-services/map-reduce-embedded/src/main/java/datawave/security/system/EmbeddedServerPrincipalProducer.java, web-services/map-reduce/src/main/java/datawave/webservice/mr/bulkresults/map/BulkResultsFileOutputMapper.java, web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/BulkResultsJobConfiguration.java
SpringCDIExtension not properly initializing the ClassPathXmlApplicationContext -- must split the resource string on commas
This was noticed when a running QueryLogic reached a point in the DocumentTransformer where it was adding cardinality information and called Document.getTimestamp() whiched caused a metadata update and a reference to MarkingFunctions which had to be resolved through Weld/CDI/Spring and failed.
CallerPrincipal and ServerPrincipal encode/decode isn't working
Also -- use an Apache Base64 class for encoding/decoding instead of infinispan
=> fixes #1010 fix SpringCDIExtension applicationContext and serialization/deserialization of DatawavePrincipals

pom.xml
* Not necessary for runtime operation
* Triggers a dependabot warning
=> Exclude dom4j 1.6.1 as a dependency

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FunctionIndexQueryExpansionVisitor.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FunctionIndexQueryExpansionVisitorTest.java
Verify that FunctionIndexQueryExpansionVisitor does not modify the
original input JEXL tree, or invalidate its lineage. In addition, verify
that the visitor returns a JEXL tree with a valid lineage.
Part of #880 and #968
=> Verify FunctionIndexQueryExpansionVisitor does not modify input tree

warehouse/query-core/src/main/java/datawave/core/iterators/TermFrequencyIterator.java, warehouse/query-core/src/main/java/datawave/core/iterators/key/TFKey.java, warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java, warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TFFactory.java, warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetFunction.java, warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java, warehouse/query-core/src/test/java/datawave/core/iterators/TermFrequencyIteratorTest.java, warehouse/query-core/src/test/java/datawave/core/iterators/key/TFKeyTest.java
Bugfix for TermFrequencyIterator: do not prune index only fields, properly calculate when to seek, do not parse keys with DatawaveKey.
=> Bugfix for TermFrequencyIterator

warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java, warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java
. Modifies the QueryIterator to remove configured Ivarator Cache Base URIS that don't exist.
Similar to #1032 but for the 2.8 branch, which predates IvaratorCacheDirs
=> Prune non-existant Ivarator Cache Base URIs

pom.xml, warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/reduce/AggregatingReducer.java
BaseIteratorEnvironment is gone in Accumulo 2.0, replaced instead with
default implementations on the IteratorEnvironment interface. Provide
an empty implementation of that interface here, to provide the same
functionality as BaseIteratorEnvironment used to.
Also, update to Accumulo 2.0.1 since it includes a CVE fix.
=> Fix compile error -- BaseIteratorEnvironment class is gone in 2.0.

warehouse/query-core/src/test/java/datawave/query/MaxExpansionRegexQueryTest.java, warehouse/query-core/src/test/java/datawave/query/testframework/AccumuloSetupHelper.java
While testing for the periodic test failures (see #637) and (#1023), I found two tests that would fail because repetitive runs would hit the list limits.
=> Datawave-MaxExapnsionRegexQueryTest-1023 

web-services/query/src/main/java/datawave/webservice/query/logic/BaseQueryLogic.java, web-services/query/src/main/java/datawave/webservice/query/logic/QueryLogic.java, web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java, web-services/query/src/test/java/datawave/webservice/query/configuration/TestBaseQueryLogic.java, web-services/query/src/test/java/datawave/webservice/query/runner/ExtendedQueryExecutorBeanTest.java, web-services/query/src/test/java/datawave/webservice/query/runner/QueryExecutorBeanTest.java
Support restricting access to query logics that have defined sets of
authorized DNs to only calling principals with an authorized DN.
Fixes #1027
=> Restrict access by DN in query execution service

warehouse/query-core/src/main/java/datawave/query/function/LimitFields.java, warehouse/query-core/src/main/java/datawave/query/jexl/DatawaveInterpreter.java, warehouse/query-core/src/test/java/datawave/query/function/HitsAreAlwaysIncludedTest.java, warehouse/query-core/src/test/java/datawave/query/util/LimitFieldsTestingIngest.java, warehouse/query-core/src/test/resources/datawave/query/QueryLogicFactory.xml
* Updated LimitFields to correctly parse hit term values
* Updated DatawaveInterpreter to correctly generate hit terms for bounded ranges and large or lists
* Added tests which demonstrated problems and now ensure fixes work
=> fixes #1123: Fixed the parsing and generation of hit terms

warehouse/query-core/src/main/java/datawave/query/predicate/ValueToAttributes.java
Stop populating a column visibility LRU cache that's never used, general cleanup.
=> Remove unused code from ValueToAttributes, general cleanup.

warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/IteratorBuildingVisitor.java, warehouse/query-core/src/main/java/datawave/query/util/sortedset/BufferedFileBackedSortedSet.java, warehouse/query-core/src/main/java/datawave/query/util/sortedset/HdfsBackedSortedSet.java, warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java
The ivarator cache directories as currently managed result in
directories being created for each QueryIterator even if they are not
actually used for HdfsBackedSortedSets.
Modify this so that the cache directories are lazily created only when
persisting data to the file system.
Note for reviewers, I modified `QueryIterator.pruneIvaratorCacheDirs()` to only remove configurations that are invalid. If there are any additional checks that should be added to this in light of the removal of actually creating the directories, please let me know.
Closes #1059
=> Lazily create ivarator cache dirs

warehouse/query-core/src/main/java/datawave/query/jexl/lookups/LookupTermsFromRegex.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/FixUnfieldedTermsVisitor.java
Enforce timeouts for regex term expansion, execute scans only if terms exist in forward/reverse maps.
=> Enforce timeouts for regex term expansion

warehouse/query-core/src/main/java/datawave/query/function/JexlEvaluation.java, warehouse/query-core/src/main/java/datawave/query/jexl/DelayedNonEventIndexContext.java, warehouse/query-core/src/test/java/datawave/query/iterator/QueryIteratorIT.java
Index only fields fetched in a delayed fashion are not added to the document returned from the QueryIterator. The query is still functionally correct but HIT_TERMS will fail to report a hit term.
=> Delayed index only field-values are now added to the candidate document.

warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ConjunctionEliminationVisitor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/DisjunctionEliminationVisitor.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/TreeEqualityVisitor.java, warehouse/query-core/src/test/java/datawave/query/index/lookup/IndexInfoTest.java, warehouse/query-core/src/test/java/datawave/query/index/lookup/IntersectionTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/AllTermsIndexedVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/BooleanOptimizationRebuildingVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ConjunctionEliminationVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/DateIndexCleanupVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/DisjunctionEliminationVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandCompositeTermsTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExpandMultiNormalizedTermsTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FixNegativeNumbersVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/FunctionIndexQueryExpansionVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/GeoWavePruningVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IsNotNullIntentVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryModelVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/RegexFunctionVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/TreeEqualityVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/TreeFlatteningRebuildingVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/UniqueExpressionTermsVisitorTest.java, warehouse/query-core/src/test/java/datawave/query/tables/facets/FacetCheckTest.java, warehouse/query-core/src/test/java/datawave/query/testframework/AbstractFunctionalQuery.java
The TreeEqualityVisitor currently only accepts two ASTJexlAcripts as
arguments for comparison. This forces developers to do more work to
utilize the TreeEqualityVisitor in tests.
Make the following changes:
* Modify the TreeEqualityVisitor to accept JexlNodes instead of
ASTJexlScripts.
* Add a static TreeEqualityVisitor.isEqual method that does not require
an instantiated Reason to be passed in.
* Add field equal to TreeEqualityVisitor.Reason so that the Reason class
may be returned and used both to assert equality and to get the reason
why two trees may not be equal.
* Add unit tests for the TreeEqualityVisitor.
Fixes #914
=> Make TreeEqualityVisitor accept JexlNodes for comparison

warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java, warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java, warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryFieldsVisitor.java, warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java, warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryFieldsVisitorTest.java
This change reduces the size of the serialized query iterator sent to the tablet servers.
=> Filter indexed, index-only, and term frequency fields to just the fields present in the query when possible.

warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/AccumuloQueryTreeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/BooleanQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/FieldQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/FunctionQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/FuzzyQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/GroupQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/ModifierQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/PhraseQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/RangeQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/builder/lucene/SlopQueryNodeBuilder.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/AbstractEvaluationPhaseFunction.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/EvaluationOnly.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Exclude.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/GetAllMatches.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/GroupBy.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Include.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/IsNotNull.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/IsNull.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/LuceneQueryFunction.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Occurrence.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Options.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Text.java, warehouse/query-core/src/main/java/datawave/query/language/functions/lucene/Unique.java, warehouse/query-core/src/main/java/datawave/query/language/parser/jexl/LuceneToJexlUUIDQueryParser.java, warehouse/query-core/src/main/java/datawave/query/language/parser/lucene/LuceneQueryParser.java, warehouse/query-core/src/main/java/datawave/query/language/parser/lucene/LuceneUUIDQueryParser.java
There are several classes related to Lucene parsing that are no longer
in used, and have been superseded by similar classes in neighboring
jexl packages.
Deprecate the unused classes.
Fixes #1200
=> Deprecate unused Lucene-related classes

warehouse/query-core/src/main/java/datawave/query/function/IndexOnlyContextCreator.java, warehouse/query-core/src/main/java/datawave/query/jexl/DelayedNonEventIndexContext.java
Not 100% positive that this is the ideal solution, but it does fix several examples of `ASTFunctionNode` eval misfire that we've encountered in testing. In each case, debugging revealed that the culprit was the index-only field(s) being omitted from the jexl context
=> Fixes #1204 - Ensure that relevant index-only fields are added to the Jexl context

warehouse/core/src/main/java/datawave/ingest/protobuf/Uid.java, warehouse/core/src/main/protobuf/Uid.proto, warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregator.java, warehouse/ingest-core/src/main/java/datawave/ingest/table/aggregator/KeepCountOnlyUidAggregator.java, warehouse/ingest-core/src/main/java/datawave/iterators/PropogatingIterator.java, warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregatorExpandedTest.java, warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/GlobalIndexUidAggregatorTest.java, warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/UidTestBuilder.java, warehouse/ingest-core/src/test/java/datawave/ingest/table/aggregator/UidTestUtils.java, warehouse/ingest-core/src/test/java/datawave/iterators/PropogatingIteratorSeekTest.java, warehouse/ingest-core/src/test/java/datawave/iterators/PropogatingIteratorTest.java
* Ensure that if there is a positive (including 0) count for an incoming
protocol buffer that we handle UIDs in the REMOVEDUID list as well as
those in the UID list. This scenario is possible if a partial major
compaction combines files adding UID(s) to the UID list and adding
other/different UID(s) to the REMOVEDUID list (where the adds of the
UIDs being removed are in a different file that isn't involved in the
major compaction).
* Switch logger to use slf4j and placeholders in the log messages.
* Add test cases for new functionality, and apply IDE clean up.
Fixes #1173
=> Don't drop UIDs in GlobalIndexUidAggregator
